# 1.Print 'Hello HCIA'.

In [2]:
print('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [5]:
a = 1; b = 4
print(a + b)

5


# 3.Define a list and replicate in three different ways.

In [8]:
test_list = [1, 2, 3, 4]
print(test_list * 2)
print(test_list + test_list)
for i in range (len(test_list)):
    test_list.append(test_list[i])
print(test_list)


[1, 2, 3, 4, 1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]


# 4.Define two lists and merge them together.

In [5]:
list1 = [1, 4, 3]
list2 = [4, 5, 5]
print(list1+list2)

[1, 4, 3, 4, 5, 5]


# 5. Get the last element of the list and print it.

In [11]:
len_list1 = len(list1)
print(list1[len_list1 - 1])

3


# 6.Define a tuple that contains only one element.

In [39]:
tpl = (1,)
print(tpl)
print(type(tpl))

(1,)
<class 'tuple'>


# 7.Define a three-line long string.

In [19]:
string_three = 'This is\nThree-line\nString'
print(string_three)

This is
Three-line
String


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [20]:
tuplee = (1,2,3,4,5)
for loop in tuplee:
    print(loop, end=' ')

1 2 3 4 5 

# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [12]:
def mul(a, b):
    result = a * b
    return result
print(mul(8,6))

48


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [22]:
import numpy as np
np_array0 = np.zeros((5, 5))
print(np_array0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [23]:
import numpy as np
np_array1 = np.zeros((4, 6))
print(np_array1)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [29]:
a = np.arange(15.)
b = np.zeros((3,5))
a = a.reshape(b.shape)
print(a)


[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [27]:
matrix_1 = np.array([[1.5, 2, 3], [4, 5, 6],[1, 2, 3]])
matrix_2 = np.array([[1.5, 2, 3], [4, 5, 6],[1, 2, 3]])
result = np.dot(matrix_1, matrix_2)
print(result)

[[13.25 19.   25.5 ]
 [32.   45.   60.  ]
 [12.5  18.   24.  ]]
